"""The contract asset: read the admitted list, and refuse to proceed on a bad one.

The audits that decide which columns reach the model are statistics, not models,
and they live in the ``ieee-cis-fraud-detection-eda`` repository as an R package. Each writes a fragment;
``stamp-contract`` merges the fragments, applies the admission policy and stamps
the fingerprint; this asset reads the result and publishes what it decided.

Nothing here recomputes a verdict. It cannot: the answer is a property of the
data, so re-deriving it per run recomputes a constant and gives the run one more
way to fail. Orchestration owns when things happen, not what is true.

The contract is committed to the repository rather than written to a bucket so
that a change arrives as a reviewable diff. "134 columns rejected by time
consistency" is something somebody should approve, not something that happens
quietly between runs.
"""

from __future__ import annotations

from datetime import UTC, datetime

import polars as pl
from dagster import AssetKey, Failure, MetadataValue, Output, asset

from fraud_detection.contract import (
    CONTRACT_FILE,
    FeatureContract,
    load_admission_rules,
)
from fraud_detection.contract.export_frame import AUDIT_FRAME_PATH, build_audit_frame
from fraud_detection.orchestration import contract_catalog
from fraud_detection.orchestration.catalog import CODE_VERSION, FEATURE_PLATFORM
from fraud_detection.orchestration.resources import BigQueryResource
from fraud_detection.schema import FEATURES_DATASET, MODEL_INPUT_TABLE, qualified

GROUP = "feature_validation"


@asset(
    owners=FEATURE_PLATFORM,
    code_version=CODE_VERSION,
    key_prefix=["fraud_detection"],
    group_name=GROUP,
    kinds={"parquet"},
    description="model_input with the declared derivations applied, for the audits to read.",
    deps=[AssetKey(["fraud_detection", "model_input"])],
)
def audit_frame(bigquery_resource: BigQueryResource):
    """The handoff to the analysis half, as an asset rather than a manual step.

    The audits are R and run outside this graph, but their *input* is pipeline data
    and belongs in it. Materialising it here is what makes "the contract was audited
    on an old export" a visible staleness in the UI instead of something nobody
    thinks to check.

    What is exported is the frame as the model receives it — `model_input` with the
    declared derivations applied. Exporting the raw table instead would leave the
    thirty derived columns unaudited, and eight of them were rejected the last time
    the whole set was measured.

    Dagster does not run R and does not know when the audits ran. It knows when this
    was produced and when the contract was stamped, and the ordering of those two is
    the only part it needs.
    """
    client = bigquery_resource.get_client()
    table = qualified(bigquery_resource.project, FEATURES_DATASET, MODEL_INPUT_TABLE)
    frame = pl.from_arrow(client.query(f"SELECT * FROM `{table}`").to_arrow())

    before = frame.width
    frame = build_audit_frame(frame)
    AUDIT_FRAME_PATH.parent.mkdir(parents=True, exist_ok=True)
    frame.write_parquet(AUDIT_FRAME_PATH)

    return Output(
        str(AUDIT_FRAME_PATH),
        metadata={
            "rows": frame.height,
            "columns": frame.width,
            "derived_columns_added": frame.width - before,
            "path": MetadataValue.path(str(AUDIT_FRAME_PATH)),
            "next": MetadataValue.md(
                "Run the audits, then stamp:\n\n"
                "```bash\ncd analysis && Rscript -e 'targets::tar_make()'\n"
                "uv run stamp-contract\n```"
            ),
        },
    )


@asset(
    owners=FEATURE_PLATFORM,
    code_version=CODE_VERSION,
    key_prefix=["fraud_detection"],
    group_name=GROUP,
    kinds={"json"},
    description="The admitted column list, as stamped from the statistical audits.",
    deps=[AssetKey(["fraud_detection", "audit_frame"])],
)
def feature_contract():
    """Read the stamped contract and publish what it decided.

    Materialising this does not recompute anything. It cannot: the verdicts are a
    property of the data, and re-deriving them per run would recompute a constant
    and give the run one more way to fail. What it does is fail loudly when the
    file on disk is missing, internally inconsistent, or older than the policy
    allows — the three ways a committed artefact stops being trustworthy.
    """
    if not CONTRACT_FILE.exists():
        raise Failure(
            description=(
                f"{CONTRACT_FILE} does not exist. The contract is produced by the "
                "audits in the audit repository and stamped by `uv run stamp-contract`; it is "
                "not generated by this run."
            )
        )

    # `from_json` recomputes the fingerprint and refuses a file whose stored hash
    # disagrees with its contents. That is the hand-edit detector, and letting it
    # fire here rather than at training time is the whole reason this asset exists.
    contract = FeatureContract.from_json(CONTRACT_FILE.read_text())
    rules = load_admission_rules()

    max_days = rules.as_dict().get("contract", {}).get("max_staleness_days")
    age_days = None
    if contract.created_at:
        created = datetime.fromisoformat(contract.created_at)
        if created.tzinfo is None:
            created = created.replace(tzinfo=UTC)
        age_days = (datetime.now(UTC) - created).days
        if max_days is not None and age_days > max_days:
            raise Failure(
                description=(
                    f"the contract is {age_days} days old and policy allows "
                    f"{max_days}. Re-run the audits in the audit repository and stamp again. "
                    "What stops 'manually materialized' from meaning 'forgotten' "
                    "is this check, not anyone's memory."
                )
            )

    minimum = rules.as_dict().get("contract", {}).get("min_admitted_features")
    admitted = contract.training_features()
    if minimum is not None and len(admitted) < minimum:
        raise Failure(
            description=(
                f"{len(admitted)} admitted features, policy requires at least "
                f"{minimum}. A contract that admits almost nothing is a broken "
                "audit, not a strict one."
            )
        )

    return Output(
        str(CONTRACT_FILE),
        metadata={
            "fingerprint": MetadataValue.text(contract.fingerprint()),
            "declared": len(contract.columns),
            "admitted": len(admitted),
            "rejected": len(contract.rejections()),
            "overridden": len(contract.overrides()),
            "age_days": age_days if age_days is not None else -1,
            "rules_digest": MetadataValue.text(rules.digest()),
            "checks": MetadataValue.text(", ".join(f.check for f in contract.fragments)),
            "tools": MetadataValue.text(
                ", ".join(sorted({f.tool for f in contract.fragments if f.tool}))
            ),
            "request_fields": len(contract.request_fields()),
            "retrieved_fields": len(contract.retrieved_fields()),
            "path": MetadataValue.path(str(CONTRACT_FILE)),
            # The column-level view, handed to the catalog in the shape it renders,
            # so the graph can answer "why is this column not in the model" without
            # anyone opening the JSON.
            **contract_catalog.contract_metadata(
                contract, AssetKey(["fraud_detection", "model_input"])
            ),
        },
    )
